export const INIT_REWARDS = {
  "Cashback Sites": [
    {
      name: "TopCashback Classic",
      icon: "TopCashback",
      browser: ["TopCashback Classic"],
      link: "https://www.topcashback.co.uk/",
    },
    {
      name: "TopCashback Plus",
      icon: "TopCashback",
      browser: ["TopCashback Plus"],
      link: "https://www.topcashback.co.uk/",
    },
    {
      name: "Quidco Basic",
      icon: "Quidco",
      browser: ["Quidco Basic"],
      link: "https://www.quidco.com/home/",
    },
    {
      name: "Quidco Premium",
      icon: "Quidco",
      browser: ["Quidco Premium"],
      link: "https://www.quidco.com/home/",
    },
  ],
  "Student Rewards": [
    {
      name: "StudentBeans",
      icon: "StudentBeans",
      browser: ["StudentBeans"],
      link: "https://www.studentbeans.com/uk",
    },
    {
      name: "UNiDAYS",
      icon: "UNiDAYS",
      browser: ["UNiDAYS"],
      link: "https://www.myunidays.com/GB/en-GB",
    },
  ],
  "Debit Cards": [
    {
      name: "Barclays",
      icon: "Barclays",
      browser: ["Barclays"],
      link: "https://www.barclays.co.uk/current-accounts/blue-rewards/barclayscashback/",
    },
    {
      name: "Halifax",
      icon: "Halifax",
      browser: ["Halifax"],
      link: "https://www.halifax.co.uk/bankaccounts/reward-extras.html",
    },
    {
      name: "HSBC",
      icon: "HSBC",
      browser: ["HSBC Home&Away"],
      link: "https://www.homeandaway.hsbc.com/gb/en-gb/",
    },
    {
      name: "Monzo",
      icon: "Monzo",
      browser: ["Monzo Tail"],
      link: "https://apps.apple.com/gb/app/verve-top-cashback-rewards/id1220787992",
    },
    {
      name: "Natwest",
      icon: "Natwest",
      browser: ["Natwest Rewards", "Natwest Priceless"],
      link: "https://www.natwest.com/",
    },
    {
      name: "Revolut",
      icon: "Revolut",
      browser: ["Revolut Rewards", "Revolut Shops"],
      link: "https://www.revolut.com/",
    },
    {
      name: "Santander",
      icon: "Santander",
      browser: ["Santander Boosts"],
      link: "https://www.santander.co.uk/",
    },
    {
      name: "Starling",
      icon: "Starling",
      browser: ["Starling Tail"],
      link: "https://www.starlingbank.com/",
    },
    {
      name: "Virgin Money",
      icon: "Virgin Money",
      browser: ["Virgin Money Cashback"],
      link: "https://www.starlingbank.com/",
    },
  ],
  "Credit Cards": [
    {
      name: "AMEX British Airways",
      icon: "AMEX",
      browser: ["AMEX British Airways"],
      link: "https://acquisition-1.americanexpress.com/en-gb/credit-cards/ba-credit-card/?linknav=en-gb-amex-cardshop-details-browse-BritAirwaysAmexCC&sourcecode=A0000EV0K9",
    },
    {
      name: "AMEX British Airways Premium Plus",
      icon: "AMEX",
      browser: ["AMEX British Airways Premium Plus"],
      link: "https://acquisition-1.americanexpress.com/en-gb/credit-cards/ba-premium-plus-credit-card/?linknav=en-gb-amex-cardshop-details-browse-BritAirwaysPremiumPlusCC&sourcecode=A0000EV0K9",
    },
    {
      name: "AMEX Platinum Cashback",
      icon: "AMEX",
      browser: ["AMEX Platinum Cashback"],
      link: "https://acquisition-1.americanexpress.com/en-gb/credit-cards/platinum-cashback-credit-card/?linknav=en-gb-amex-cardshop-details-browse-PlatinumCashBackCC&sourcecode=A0000EV0K9",
    },
    {
      name: "AMEX Platinum Everyday Cashback",
      icon: "AMEX",
      browser: ["AMEX Platinum Everyday Cashback"],
      link: "https://acquisition-1.americanexpress.com/en-gb/credit-cards/platinum-cashback-everyday-credit-card/?linknav=en-gb-amex-cardshop-details-browse-PlatCashBackEverydayCC&sourcecode=A0000EV0K9",
    },
    {
      name: "AMEX Preferred Rewards Gold",
      icon: "AMEX",
      browser: ["AMEX Preferred Rewards Gold"],
      link: "https://acquisition-1.americanexpress.com/en-gb/credit-cards/gold-credit-card/?linknav=en-gb-amex-cardshop-details-browse-GoldCreditCard&sourcecode=A0000EV0K9",
    },
    {
      name: "Barclaycard",
      icon: "Barclaycard",
      browser: ["Barclaycard"],
      link: "https://www.barclaycard.co.uk/personal/customer/barclaycard-cashback-rewards",
    },
  ],
  "Employee Perks": [
    {
      name: "Blue Light Card",
      icon: "Blue Light Card",
      browser: ["Blue Light Card"],
      link: "https://www.bluelightcard.co.uk/",
    },
    {
      name: "Charity Worker Discounts",
      icon: "Charity Worker Discounts",
      browser: ["Charity Worker Discounts"],
      link: "https://www.charityworkerdiscounts.com/",
    },
    {
      name: "MyActiveDiscounts",
      icon: "MyActive Discounts",
      browser: ["MyActive Discounts"],
      link: "https://www.myactivediscounts.co.uk/",
    },
    {
      name: "MyGymDiscounts",
      icon: "MyGym Discounts",
      browser: ["MyGym Discounts"],
      link: "https://www.mygymdiscounts.co.uk/",
    },
    {
      name: "Perks at Work",
      icon: "Perks at Work",
      browser: ["Perks at Work"],
      link: "https://www.perksatwork.com/",
    },
    {
      name: "Reward Gateway",
      icon: "Reward Gateway",
      browser: ["Reward Gateway", "Reward Gateway Smart Spend"],
      link: "https://www.revolut.com/",
    },
  ],
  Mobile: [
    {
      name: "EE",
      icon: "EE",
      browser: ["EE Airtime"],
      link: "https://airtimerewards.app.link/3iho9VwwTBb",
    },
    {
      name: "Giffgaff",
      icon: "Giffgaff",
      browser: ["Giffgaff Airtime"],
      link: "https://airtimerewards.app.link/3iho9VwwTBb",
    },
    {
      name: "O2",
      icon: "O2",
      browser: ["O2 Priority", "O2 Airtime"],
      link: "https://www.o2.co.uk/",
    },
    {
      name: "Three",
      icon: "Three",
      browser: ["Three Airtime", "Three Plus"],
      link: "https://airtimerewards.app.link/3iho9VwwTBb",
    },
    {
      name: "Virgin Media",
      icon: "Virgin Media",
      browser: ["Virgin Media Priority"],
      link: "https://priority.o2.co.uk/register",
    },
    {
      name: "Vodafone",
      icon: "Vodafone",
      browser: ["Vodafone Airtime", "Vodafone VeryMe"],
      link: "https://airtimerewards.app.link/3iho9VwwTBb",
    },
  ],
  Insurance: [
    {
      name: "AA",
      icon: "AA",
      browser: ["AA Smart Benefits"],
      link: "https://www.theaa.com/",
    },
    {
      name: "AXA",
      icon: "AXA",
      browser: ["AXA"],
      link: "https://www.axahealth.co.uk/",
    },
    {
      name: "Vitality",
      icon: "Vitality",
      browser: ["Vitality", "Vitality Rewards"],
      link: "https://www.axahealth.co.uk/",
    },
  ],
  "Supermarket Loyalty Schemes": [
    {
      name: "Lidl Plus",
      icon: "Lidl",
      browser: ["Lidl Plus"],
      link: "https://apps.apple.com/gb/app/lidl-plus/id1238611143?l=en",
    },
    {
      name: "Sainbury's Nectar",
      icon: "Sainbury's Nectar",
      browser: ["Sainbury's Nectar", "Nectar"],
      link: "https://www.nectar.com/",
    },
    {
      name: "Tesco Clubcard",
      icon: "Tesco Clubcard",
      browser: ["Tesco Clubcard Reward Partners"],
      link: "https://secure.tesco.com/clubcard/spend-vouchers",
    },
  ],
  Other: [
    {
      name: "16-17 Saver Railcard",
      icon: "Railcard",
      browser: ["Railcard 16-17 Saver Railcard"],
      link: "https://www.railcard.co.uk/",
    },
    {
      name: "16-25 Railcard",
      icon: "Railcard",
      browser: ["Railcard 16-25 Railcard"],
      link: "https://www.railcard.co.uk/",
    },
    {
      name: "26-30 Railcard",
      icon: "Railcard",
      browser: ["Railcard 26-30 Railcard"],
      link: "https://www.railcard.co.uk/",
    },
    {
      name: "Disabled Persons Railcard",
      icon: "Railcard",
      browser: ["Railcard Disabled Persons Railcard"],
      link: "https://www.railcard.co.uk/",
    },
    {
      name: "Family & Friends Railcard",
      icon: "Railcard",
      browser: ["Railcard Family & Friends Railcard"],
      link: "https://www.railcard.co.uk/",
    },
    {
      name: "Network Railcard",
      icon: "Railcard",
      browser: ["Railcard Network Railcard"],
      link: "https://www.railcard.co.uk/",
    },
    {
      name: "Senior Railcard",
      icon: "Railcard",
      browser: ["Railcard Senior Railcard"],
      link: "https://www.railcard.co.uk/",
    },
    {
      name: "Two Together Railcard",
      icon: "Railcard",
      browser: ["Railcard Two Together Railcard"],
      link: "https://www.railcard.co.uk/",
    },
    {
      name: "Veterans Railcard",
      icon: "Railcard",
      browser: ["Railcard Veterans Railcard"],
      link: "https://www.railcard.co.uk/",
    },
    {
      name: "Tastecard",
      icon: "Tastecard",
      browser: [
        "Tastecard Days Out",
        "Tastecard Retail",
        "Tastecard Pizza Delivery",
      ],
      link: "https://www.tastecard.co.uk/",
    },
  ],
};
